name: Checks
on: [push]
jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # No immediate action required for Node.js 20 compatibility
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3 # No immediate action required for Node.js 20 compatibility

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # No immediate action required for Node.js 20 compatibility

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

      - name: Cleanup
        run: docker-compose down