name: Checks
on: [push]
jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # Updated to v2 to avoid using node12
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v3 # Updated to v3 to avoid node12 deprecation

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Ensures buildx is set up correctly for future-proof builds

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

      - name: Cleanup
        run: docker-compose down # Cleanup resources after running tests and linting
